In [1]:
import pandas as pd
import numpy as np

In [2]:
s = pd.Series([1, 2, 3, 4, 5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
s.values

array([1, 2, 3, 4, 5], dtype=int64)

In [4]:
s.name = "Power Case"

In [5]:
s

0    1
1    2
2    3
3    4
4    5
Name: Power Case, dtype: int64

In [6]:
s.values

array([1, 2, 3, 4, 5], dtype=int64)

In [7]:
k = np.array([1, 2, 3])
k

array([1, 2, 3])

In [8]:
type(k)

numpy.ndarray

In [9]:
type(s)

pandas.core.series.Series

In [10]:
type(s.values)

numpy.ndarray

In [11]:
s[0]
k[0]

1

In [12]:
s[0]

1

In [13]:
k[0]

1

In [14]:
k[1]

2

In [15]:
s[3]

4

In [17]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [18]:
s.index = ['h']

ValueError: Length mismatch: Expected axis has 5 elements, new values have 1 elements

In [19]:
s.index = [5, 3, 2, 2, 1]

In [20]:
s

5    1
3    2
2    3
2    4
1    5
Name: Power Case, dtype: int64

In [21]:
s[2]

2    3
2    4
Name: Power Case, dtype: int64

In [23]:
s.index = range(10, 20, 2)

In [24]:
s

10    1
12    2
14    3
16    4
18    5
Name: Power Case, dtype: int64

In [25]:
s.index = [1.0, 2.0, 3.0, 4.0, 5.0]

In [26]:
s

1.0    1
2.0    2
3.0    3
4.0    4
5.0    5
Name: Power Case, dtype: int64

In [28]:
for i in s:
    print(i)

1
2
3
4
5
