In [1]:
import pandas as pd
import numpy as np

In [2]:
s = pd.Series([1, 2, 3, 4, 5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
s.values

array([1, 2, 3, 4, 5], dtype=int64)

In [4]:
s.name = "Power Case"

In [5]:
s

0    1
1    2
2    3
3    4
4    5
Name: Power Case, dtype: int64

In [6]:
s.values

array([1, 2, 3, 4, 5], dtype=int64)

In [7]:
k = np.array([1, 2, 3])
k

array([1, 2, 3])

In [8]:
type(k)

numpy.ndarray

In [9]:
type(s)

pandas.core.series.Series

In [10]:
type(s.values)

numpy.ndarray

In [11]:
s[0]
k[0]

1

In [12]:
s[0]

1

In [13]:
k[0]

1

In [14]:
k[1]

2

In [15]:
s[3]

4

In [16]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [17]:
try:
    s.index = ['h']
except ValueError:
    print("Value Error")

Value Error


In [18]:
s.index = [5, 3, 2, 2, 1]

In [19]:
s

5    1
3    2
2    3
2    4
1    5
Name: Power Case, dtype: int64

In [20]:
s[2]

2    3
2    4
Name: Power Case, dtype: int64

In [21]:
s.index = range(10, 20, 2)

In [22]:
s

10    1
12    2
14    3
16    4
18    5
Name: Power Case, dtype: int64

In [23]:
s.index = [1.0, 2.0, 3.0, 4.0, 5.0]

In [24]:
s

1.0    1
2.0    2
3.0    3
4.0    4
5.0    5
Name: Power Case, dtype: int64

In [25]:
for i in s:
    print(i)

1
2
3
4
5


In [26]:
s.iloc[2]

3

In [27]:
s.iloc[0]

1

In [28]:
s[[1.0, 3.0]]

1.0    1
3.0    3
Name: Power Case, dtype: int64

In [29]:
s.iloc[[1, 2]]

2.0    2
3.0    3
Name: Power Case, dtype: int64

In [30]:
s[2.0:5.0]

2.0    2
3.0    3
4.0    4
5.0    5
Name: Power Case, dtype: int64

In [31]:
s.iloc[2:5]

3.0    3
4.0    4
5.0    5
Name: Power Case, dtype: int64

In [32]:
s[2.0:6.0]

2.0    2
3.0    3
4.0    4
5.0    5
Name: Power Case, dtype: int64

In [33]:
s.iloc[0:1]

1.0    1
Name: Power Case, dtype: int64

In [34]:
s.iloc[0:10]

1.0    1
2.0    2
3.0    3
4.0    4
5.0    5
Name: Power Case, dtype: int64

In [35]:
s[7.0:8.0]

Series([], Name: Power Case, dtype: int64)

In [36]:
s

1.0    1
2.0    2
3.0    3
4.0    4
5.0    5
Name: Power Case, dtype: int64

In [37]:
s>2

1.0    False
2.0    False
3.0     True
4.0     True
5.0     True
Name: Power Case, dtype: bool

In [38]:
s[s>2]

3.0    3
4.0    4
5.0    5
Name: Power Case, dtype: int64

In [39]:
s.mean()

3.0

In [40]:
s.std()

1.5811388300841898

In [41]:
s[s>s.mean()]

4.0    4
5.0    5
Name: Power Case, dtype: int64

In [42]:
s[(s>s.mean()) | (s<2) ]

1.0    1
4.0    4
5.0    5
Name: Power Case, dtype: int64

In [43]:
s[(s>s.mean()) | ~(s<2) ]

2.0    2
3.0    3
4.0    4
5.0    5
Name: Power Case, dtype: int64

In [44]:
s * 5

1.0     5
2.0    10
3.0    15
4.0    20
5.0    25
Name: Power Case, dtype: int64

In [45]:
s + 5

1.0     6
2.0     7
3.0     8
4.0     9
5.0    10
Name: Power Case, dtype: int64

In [46]:
s / 5

1.0    0.2
2.0    0.4
3.0    0.6
4.0    0.8
5.0    1.0
Name: Power Case, dtype: float64

In [47]:
s - 10

1.0   -9
2.0   -8
3.0   -7
4.0   -6
5.0   -5
Name: Power Case, dtype: int64

In [48]:
s.sum()

15

In [49]:
s[1.0:3.0].mean()

2.0

In [50]:
s[1.0:13.0].mean()

3.0

In [51]:
np.log(s)

1.0    0.000000
2.0    0.693147
3.0    1.098612
4.0    1.386294
5.0    1.609438
Name: Power Case, dtype: float64

In [52]:
s[1.0] = 5
s.iloc[2] = 3
s.iloc[-1] = 1
s[(s==2)|(s==4)]=6
s

1.0    5
2.0    6
3.0    3
4.0    6
5.0    1
Name: Power Case, dtype: int64

In [53]:
df = pd.DataFrame({
    'population': [100, 200, 300, 400, 500],
    'sex ratio': [20, 80, 40, 70, 50],
    'life expantancy': [70, 75, 90, 85, 100],
    'remarks': ['a', 'b', 'c', 'd', 'e']
})

In [54]:
df

population  sex ratio  life expantancy remarks
0         100         20               70       a
1         200         80               75       b
2         300         40               90       c
3         400         70               85       d
4         500         50              100       e

In [55]:
df.index = ['India', 'USA', 'Japan', 'Canada', 'Hong Kong']

In [56]:
df

population  sex ratio  life expantancy remarks
India             100         20               70       a
USA               200         80               75       b
Japan             300         40               90       c
Canada            400         70               85       d
Hong Kong         500         50              100       e

In [57]:
df.iloc[0]

population         100
sex ratio           20
life expantancy     70
remarks              a
Name: India, dtype: object

In [58]:
print(df.iloc[0]['population'])
print(df.iloc[0][0])
print(df.iloc[0].iloc[0])

100
100
100


In [59]:
df.index

Index(['India', 'USA', 'Japan', 'Canada', 'Hong Kong'], dtype='object')

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, India to Hong Kong
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   population       5 non-null      int64 
 1   sex ratio        5 non-null      int64 
 2   life expantancy  5 non-null      int64 
 3   remarks          5 non-null      object
dtypes: int64(3), object(1)
memory usage: 200.0+ bytes


In [61]:
df.shape

(5, 4)

In [62]:
df.size

20

In [63]:
df

population  sex ratio  life expantancy remarks
India             100         20               70       a
USA               200         80               75       b
Japan             300         40               90       c
Canada            400         70               85       d
Hong Kong         500         50              100       e

In [64]:
df.describe()

population  sex ratio  life expantancy
count    5.000000   5.000000         5.000000
mean   300.000000  52.000000        84.000000
std    158.113883  23.874673        11.937336
min    100.000000  20.000000        70.000000
25%    200.000000  40.000000        75.000000
50%    300.000000  50.000000        85.000000
75%    400.000000  70.000000        90.000000
max    500.000000  80.000000       100.000000

In [65]:
df.dtypes

population          int64
sex ratio           int64
life expantancy     int64
remarks            object
dtype: object

In [66]:
df.dtypes.value_counts()

int64     3
object    1
dtype: int64

In [67]:
df['population']

India        100
USA          200
Japan        300
Canada       400
Hong Kong    500
Name: population, dtype: int64

In [68]:
df.loc['India']

population         100
sex ratio           20
life expantancy     70
remarks              a
Name: India, dtype: object

In [69]:
df.iloc[1]

population         200
sex ratio           80
life expantancy     75
remarks              b
Name: USA, dtype: object

In [70]:
df['population'].to_frame()

population
India             100
USA               200
Japan             300
Canada            400
Hong Kong         500

In [71]:
df[['population', 'remarks']]

population remarks
India             100       a
USA               200       b
Japan             300       c
Canada            400       d
Hong Kong         500       e

In [72]:
df[1:3]

population  sex ratio  life expantancy remarks
USA           200         80               75       b
Japan         300         40               90       c

In [73]:
df.loc[['India', 'USA']]

population  sex ratio  life expantancy remarks
India         100         20               70       a
USA           200         80               75       b

In [74]:
df.loc['India': 'Japan']

population  sex ratio  life expantancy remarks
India         100         20               70       a
USA           200         80               75       b
Japan         300         40               90       c

In [75]:
# Errors:-
# df.loc[1:3]
# df['population': 'remarks']
# df.loc['India': 'Japan', ['population': 'life expantancy']]

In [76]:
df.loc['India': 'Japan', 'population']

India    100
USA      200
Japan    300
Name: population, dtype: int64

In [77]:
df.loc['India': 'Japan', 'population'].to_frame()

population
India         100
USA           200
Japan         300

In [78]:
df.loc['India': 'Japan', ['population', 'life expantancy']]

population  life expantancy
India         100               70
USA           200               75
Japan         300               90

In [79]:
df.iloc[2:4, [2, 3]]

life expantancy remarks
Japan                90       c
Canada               85       d

In [80]:
df.iloc[2:4, [2]]

life expantancy
Japan                90
Canada               85

In [81]:
df.iloc[2:4, 2].to_frame()

life expantancy
Japan                90
Canada               85

In [82]:
df['population'] > 300

India        False
USA          False
Japan        False
Canada        True
Hong Kong     True
Name: population, dtype: bool

In [83]:
df.loc[df['population'] > 300]

population  sex ratio  life expantancy remarks
Canada            400         70               85       d
Hong Kong         500         50              100       e

In [84]:
df.drop(['Canada', 'Japan'])

population  sex ratio  life expantancy remarks
India             100         20               70       a
USA               200         80               75       b
Hong Kong         500         50              100       e

In [85]:
df

population  sex ratio  life expantancy remarks
India             100         20               70       a
USA               200         80               75       b
Japan             300         40               90       c
Canada            400         70               85       d
Hong Kong         500         50              100       e

In [87]:
df.drop(columns=['population'])

sex ratio  life expantancy remarks
India             20               70       a
USA               80               75       b
Japan             40               90       c
Canada            70               85       d
Hong Kong         50              100       e

In [89]:
df[['population', 'sex ratio']] / 100

population  sex ratio
India             1.0        0.2
USA               2.0        0.8
Japan             3.0        0.4
Canada            4.0        0.7
Hong Kong         5.0        0.5